### ISSUE TITLE
possible \x08 character in seeds.rb

### ISSUE THREAD

**Issue by ghukill** [DigitalNZ/supplejack_docker#25]
Excited to see there was a Docker install for supplejack, gave the install a go.  Builds went fine, but during `docker-compose up` saw the following errors from the manager:

```
manager        | WARNING: Use strings for Figaro configuration. 1 was converted to "1".
manager        | WARNING: Use strings for Figaro configuration. 1 was converted to "1".
manager        | config.eager_load is set to nil. Please update your config/environments/*.rb files accordingly:
manager        | 
manager        |   * development - set it to false
manager        |   * test - set it to false (unless you use a tool that preloads your test environment)
manager        |   * production - set it to true
manager        | 
manager        | rails aborted!
manager        | SyntaxError: /var/manager/db/seeds.rb:2: Invalid char `\x08' in expression
manager        | /usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
manager        | /usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
manager        | /usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
manager        | /usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
manager        | /usr/local/bundle/gems/mongoid-6.3.0/lib/mongoid/railties/database.rake:20:in `block (2 levels) in <top (required)>'
manager        | /usr/local/bundle/gems/airbrake-7.1.1/lib/airbrake/rake.rb:19:in `execute'
manager        | /usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
manager        | /usr/local/bundle/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
manager        | /usr/local/bundle/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
manager        | /usr/local/bundle/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
manager        | script/rails:6:in `require'
manager        | script/rails:6:in `<main>'
manager        | Tasks: TOP => db:seed
manager        | (See full trace by running task with --trace)
```

Looking at the host version of `manager/db/seeds.rb`, noticed what looked like that character in sublime text:

<img width="258" alt="Screen Shot 2019-03-21 at 7 53 21 AM" src="https://user-images.githubusercontent.com/1753087/54750744-22fee180-4baf-11e9-82ec-88b884920c15.png">

Removing that character and rebuilding appears to have helped?  `docker-compose up` looks to be successful, and I can login.  Looking forward to taking it for a spin!

Building on a Mac 10.14.3, Docker Desktop CE, Engine 18.09.2, Compose 1.23.2.

**Comment by theomarkkuspaul** [comment]
Hi Graham, hope all is well! Thanks for letting us know about this issue. We will take a look into this soon. Be in touch!

**Comment by theomarkkuspaul** [comment]
Hi @ghukill, many thanks again for pointing this out. We have updated the manager `db/seed.rb` file and reflected the change in the SJ Docker repo. Cheers!

**Comment by ghukill** [comment]
Awesome, thanks @theomarkkuspaul!
