### ISSUE TITLE
"translation missing: en.users.blank_token`

### ISSUE THREAD

**Issue by telezoic** [DigitalNZ/supplejack_docker#27]
Hi Folks, 

I'm working with your new docker repo and I bumping into a error when I try an view the API url.

It looks like this:

`errors": "translation missing: en.users.blank_token`

I can't say I know anything about translation errors but the little bit I have learned points me to a locales/en.yml. 

This file looks the same (to me) across all the SJ installs I'm running (4). but I only see this error with this (docker) build. [The others are much older]

Also, in the manager under API admin drop down, each of the links takes me to page with a error message: 

		"We're sorry, but something went wrong"

I'm hoping someone could point me a path to solving these problems :)

Thanks, 

D.

**Comment by theomarkkuspaul** [comment]
Hi Dan,

Hope all is well and thanks for letting us know about this issue. We will get onto this as soon as we can and we appreciate your patience as always!

Best,
Theo

**Comment by tim-boost** [comment]
Hi Dan,

I've investigated the issues you were running into last week and have pushed a fix out to the supplejack_docker repo. If you run `docker-compose down`, pull the latest changes in git then run `docker-compose up --build` then you'll get the latest changes build and running in your SJ docker stack. 

The reason why the production admin tabs don't work in Supplejack Docker is that they are expecting production API keys to be configured in the sample_rails_app. You can see this in the logs if you bash onto the docker container running the manager. Which you can do by running `docker ps` followed by `docker exec -it <container id here of the manager> /bin/bash` from here in the manager container you can run `tail -f log/staging.log` to see the error which mentions which API key it's expecting to be present. However we don't recommend using the SJ docker stack in a production environment.

Cheers,
Tim

**Comment by telezoic** [comment]
Thanks @tim-boost!

I pulled the changes and the error is gone. Thanks again! 

However . . . I can't seem to get a harvest to function. In the modal window the preview comes though and underneath there's a 403 error. Like this:
```
RestClient::Forbidden
403 Forbidden

    /var/worker/vendor/cache/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response'
    /var/worker/vendor/cache/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
    /var/worker/vendor/cache/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
    /var/worker/vendor/cache/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
    /usr/local/lib/ruby/2.5.0/net/http.rb:910:in `start'
    /var/worker/vendor/cache/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
    /var/worker/vendor/cache/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
    /var/worker/vendor/cache/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
    /var/worker/vendor/cache/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient.rb:71:in `post'
    /var/worker/app/workers/api_update_worker.rb:31:in `perform'
    /var/worker/app/workers/harvest_worker.rb:85:in `post_to_api'
    /var/worker/app/workers/preview_worker.rb:94:in `enrich_record'
    /var/worker/app/workers/preview_worker.rb:37:in `block in perform'
    /var/worker/app/models/harvest_job.rb:61:in `block in records'
    /var/worker/vendor/cache/ruby/2.5.0/bundler/gems/supplejack_common-b598e75beadc/lib/supplejack_common/paginated_collection.rb:143:in `yield_from_records'
    /var/worker/vendor/cache/ruby/2.5.0/bundler/gems/supplejack_common-b598e75beadc/lib/supplejack_common/paginated_collection.rb:33:in `block in each'
    /var/worker/vendor/cache/ruby/2.5.0/bundler/gems/supplejack_common-b598e75beadc/lib/supplejack_common/paginated_collection.rb:30:in `each'
    /var/worker/vendor/cache/ruby/2.5.0/bundler/gems/supplejack_common-b598e75beadc/lib/supplejack_common/paginated_collection.rb:30:in `each'
    /var/worker/app/models/harvest_job.rb:60:in `each_with_index'
    /var/worker/app/models/harvest_job.rb:60:in `records'
    /var/worker/app/workers/preview_worker.rb:34:in `perform'
    /var/worker/vendor/cache/ruby/2.5.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:185:in `execute_job'
    /var/worker/vendor/cache/ruby/2.5.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
    /var/worker/vendor/cache/ruby/2.5.0/gems/sidekiq-5.2.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
    /var/worker/vendor/cache/ruby/2.5.0/gems/sidekiq-5.2.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
    /var/worker/vendor/cache/ruby/2.5.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:166:in `block in process'
    /var/worker/vendor/cache/ruby/2.5.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:137:in `block (6 levels) in dispatch'
    /var/worker/vendor/cache/ruby/2.5.0/gems/sidekiq-5.2.3/lib/sidekiq/job_retry.rb:108:in `local'
    /var/worker/vendor/cache/ruby/2.5.0/gems/sidekiq-5.2.3/lib/sidekiq/processor.rb:136:in `block (5 levels) in dispatch'
    /var/worker/vendor/cache/ruby/2.5.0/gems/sidekiq-5.2.3/lib/sidekiq/rails.rb:42:in `block in call'
    /var/worker/vendor/cache/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap' 
```

and from the api log, I can see the 403 being delivered, but nothing else that stands out:

```
API log:

worker         | Started POST "//previews" for 172.18.0.5 at 2019-04-16 21:03:02 +0000
worker         | Processing by PreviewsController#create as */*
worker         |   Parameters: {"preview"=>{"format"=>"xml", "harvest_job"=>{"parser_code"=>"class Test < SupplejackCommon::Xml::Base\r\n  \r\n  base_url \"http://eln-sj4.is.sfu.ca/data/carefoot.xml\"\r\n\r\n\r\n\r\n  namespaces dc:\"http://purl.org/dc/elements/1.1/\"\r\n  \r\n  record_selector \"//record\"\r\n\r\n  \r\n  record_format :xml\r\n  \r\n\r\n  \r\n   attributes :jurisdiction, default: \"British Columbia\"\r\n  \r\n  attribute :display_content_partner, default: 'Vancouver Island University'\r\n  \r\n  \r\n\tattribute :landing_url do fetch(\"//header/identifier\").mapping('oai:viuspace.viu.ca:' => 'http://hdl.handle.net/')\r\n  end\r\n  \r\n  attributes :source_url do\r\n   get(:landing_url)\r\nend\r\n  \r\n  attributes :internal_identifier do\r\n    get(:landing_url).downcase\r\nend\r\n  \r\n  \r\n  \r\n     attribute :description, xpath: \"//dc:description\", truncate: 170 do\r\n       get(:description).first\r\nend\r\n  \r\n  \r\n \r\n  attribute :pre_date, xpath: \"//dc:date\"  do\r\n    get(:pre_date).first\r\n\r\n    end\r\n\r\n    \r\n\r\n  \r\n  attribute :display_date do\r\n    get(:pre_date).truncate(4, \"\")\r\nend\r\n\r\n  attribute :creator do fetch(\"//dc:creator\").join ' ; '\r\n    \r\nend\r\n  \r\n  \r\n  attributes :category, default: \"text\" \r\nattributes :rights, xpath: \"//dc:rights\" \r\n\r\n  attributes :subject, xpath: \"//dc:subject\", mappings: {'Postacards' => 'Postcards'}\r\n  \r\n  attribute :title, xpath: \"//dc:title\"\r\n  \r\n  \r\n  #attribute :coverage, xpath: \"//dc:coverage\", mappings: {'\\d-\\d+' => ''}\r\n  attribute :coverage do\r\n    fetch('//dc:coverage').find_without(/\\d\\d\\d\\d-\\d\\d\\d\\d+/)\r\nend\r\n\r\n  \r\n  attribute :locations do\r\n    splits = get(:coverage).split(',').select(:last)\r\n    geoID = splits.split('/').select(:last)\r\n    \r\n    front = \"http://api.geonames.org/get?geonameId=\"  #timeout with old http://ws.geonames.org URL\r\n  \ttail = \"&style=full&username=siftond\"\r\n    mid = geoID\r\n    \r\n    compose(front,mid,tail)\r\n  end\r\n  \r\n  enrichment :get_lat_meta, priority: -4, required_for_active_record: false do \r\n    \r\n      requires :uri do\r\n        primary[:locations].first\r\n    end\r\n    \r\n    url requirements[:uri]\r\n    format :xml\r\n   \t\r\n  attribute :locations do\r\n    [\r\n      {lat: fetch(\"//geoname/lat\").first, \r\n        lng: fetch(\"//geoname/lng\").first,\r\n        geonamesId: fetch(\"//geoname/geonameId\").first}\r\n    ]\r\n  end\r\n \r\nend\r\n  \r\n  \r\n  #you could target the OCR bitstream and run an enrichment to incorporate it in the same \r\n  #way we pull for ODW govdocs, and enable fulltext searching for dspace (and other, harvests)\r\n  #----\r\n\r\n  \r\n  \r\n  \r\n  attribute :thumbnail_url, xpath: '//dc:identifier' do\r\n    get(:thumbnail_url).find_with('sequence').mapping('sequence=3' => 'sequence=7', 'sequence=5' => 'sequence=7', 'viuspace.viu.ca' => 'viurrspace.ca')\r\n  end\r\n\r\nend", "parser_id"=>"5cb4e022b0cb96001261f94d", "environment"=>"preview", "index"=>"0", "limit"=>"1", "user_id"=>"5ca5918b70c32000060c310b"}}}
worker         | MONGODB | mongodb:27017 | worker_development.insert | STARTED | {"insert"=>"abstract_jobs", "ordered"=>true, "lsid"=>{"id"=><BSON::Binary:0x47421166711620 type=uuid data=0x2ef6d6c8a74e4c11...>}, "documents"=>[{"_id"=>BSON::ObjectId('5cb64306755be20001115e66'), "records_count"=>0, "processed_count"=>0, "invalid_rec...
worker         | MONGODB | mongodb:27017 | worker_development.insert | SUCCEEDED | 0.001s
worker         | MONGODB | mongodb:27017 | worker_development.insert | STARTED | {"insert"=>"previews", "ordered"=>true, "lsid"=>{"id"=><BSON::Binary:0x47421166711620 type=uuid data=0x2ef6d6c8a74e4c11...>}, "documents"=>[{"_id"=>BSON::ObjectId('5cb64306755be20001115e67'), "format"=>"xml", "status"=>"New preview record initialised....
sidekiq        | 2019-04-16T21:01:46.591Z 1 TID-go7wpq7jp PreviewWorker JID-bce6cbc64725b5fb70f45898 INFO: done: 0.31 sec
worker         | MONGODB | mongodb:27017 | worker_development.insert | SUCCEEDED | 0.000s
sidekiq        | 2019-04-16T21:03:02.798Z 1 TID-go7wpq6pp PreviewWorker JID-8b2a80f6d3e9ebbea2115fd5 INFO: start
sidekiq        | 2019-04-16T21:03:02.830Z 1 TID-go7wpq6pp PreviewWorker JID-8b2a80f6d3e9ebbea2115fd5 INFO: Acquired lock for eln-sj4.is.sfu.ca, requesting URL
sidekiq        | 2019-04-16T21:03:02.830Z 1 TID-go7wpq6pp PreviewWorker JID-8b2a80f6d3e9ebbea2115fd5 INFO: Retrying RestClient request http://eln-sj4.is.sfu.ca/data/carefoot.xml
api            | Filter chain halted as :authenticate_user! rendered or redirected
api            | Completed 403 Forbidden in 6ms (Views: 2.3ms | Solr: 0.0ms)
api            | 
api            | 
api            | Started POST "//harvester/records.json" for 172.18.0.9 at 2019-04-16 21:03:03 +0000
api            | Processing by SupplejackApi::Harvester::RecordsController#create as JSON
api            |   Parameters: {"record"=>{"priority"=>0, "jurisdiction"=>["British Columbia"], "display_content_partner"=>["Vancouver Island University"], "landing_url"=>["http://hdl.handle.net/10613/1779"], "source_url"=>["http://hdl.handle.net/10613/1779"], "internal_identifier"=>["http://hdl.handle.net/10613/1779"], "description"=>["Arabian recipes, Caribbean recipes, Chilean recipes, chines recipes, Doukhobor recipes, Dutch recipes, Filipino recipes, German recipes, Greek recipes, recipes of Indi..."], "pre_date"=>["2014-05-07T15:29:31Z"], "display_date"=>["2014"], "creator"=>[], "category"=>["text"], "rights"=>[], "subject"=>["International cooking"], "title"=>["Folkfest recipe book [title page]"], "coverage"=>["Saskatoon, Saskatchewan, Canada, http://sws.geonames.org/6141256"], "locations"=>["http://api.geonames.org/get?geonameId=6141256&style=full&username=siftond"], "thumbnail_url"=>["https://viurrspace.ca/bitstream/handle/10613/1779/CarefootFolkfest.pdf?sequence=7"], "source_id"=>"supplejack_docker"}, "required_fragments"=>[], "preview"=>true, "api_key"=>"KJ64DC023FFO"}
api            | MONGODB | mongodb:27017 | supplejack_api_development1.find | STARTED | {"find"=>"users", "filter"=>{"authentication_token"=>"KJ64DC023FFO"}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true, "lsid"=>{"id"=><BSON::Binary:0x47419336400340 type=uuid data=0x4664cf7b1e54448b...>}}
api            | MONGODB | mongodb:27017 | supplejack_api_development1.find | SUCCEEDED | 0.001s
api            | MONGODB | mongodb:27017 | supplejack_api_development1.find | STARTED | {"find"=>"users", "filter"=>{"authentication_token"=>"KJ64DC023FFO"}, "sort"=>{"_id"=>1}, "limit"=>1, "singleBatch"=>true, "lsid"=>{"id"=><BSON::Binary:0x47419336400340 type=uuid data=0x4664cf7b1e54448b...>}}
api            | MONGODB | mongodb:27017 | supplejack_api_development1.find | SUCCEEDED | 0.001s
api            | [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.09ms)
api            | Filter chain halted as :authenticate_user! rendered or redirected
sidekiq        | 2019-04-16T21:03:03.224Z 1 TID-go7wpq6pp PreviewWorker JID-8b2a80f6d3e9ebbea2115fd5 INFO: GET (0.3937): http://eln-sj4.is.sfu.ca/data/carefoot.xml, started 2019-04-16T21:03:02Z
worker         | [active_model_serializers] Rendered ActiveModel::Serializer::Null with Preview (0.49ms)
worker         | Completed 200 OK in 8ms (Views: 1.0ms)
worker         | 
worker         | 
worker         | Started GET "/previews/5cb64306755be20001115e67.json" for 172.18.0.5 at 2019-04-16 21:03:04 +0000
worker         | Processing by PreviewsController#show as JSON
worker         |   Parameters: {"id"=>"5cb64306755be20001115e67"}
worker         | MONGODB | mongodb:27017 | worker_development.find | STARTED | {"find"=>"previews", "filter"=>{"_id"=>BSON::ObjectId('5cb64306755be20001115e67')}, "lsid"=>{"id"=><BSON::Binary:0x47421166711620 type=uuid data=0x2ef6d6c8a74e4c11...>}}
worker         | MONGODB | mongodb:27017 | worker_development.find | SUCCEEDED | 0.001s
worker         | [active_model_serializers] Rendered ActiveModel::Serializer::Null with Preview (0.82ms)
sidekiq-api    | 2019-04-16T21:02:05.953Z 8 TID-gt9sw2su4 SupplejackApi::IndexRemainingRecordsInQueue JID-ed4af7e0c47803cf9d83de94 INFO: done: 0.007 sec
sidekiq-api    | 2019-04-16T21:03:05.718Z 8 TID-gt9tjfcj0 SupplejackApi::IndexRemainingRecordsInQueue JID-5285b6427d8aea78353778b8 INFO: start
```

I made a pair of parsers pointing to different endpoints, I can query the endpoints from the console and confirm that they are up. 

```
irb(main):002:0> RestClient.get 'http://eln-sj4.is.sfu.ca/data/carefoot.xml' 
=> <RestClient::Response 200 "<repository...">
irb(main):001:0> RestClient.get 'http://unbc.arcabc.ca/oai2'
=> <RestClient::Response 200 "<?xml versi...">

````

I was thinking this might be an environment firewall/port kind of thing, but two separate builds (in the cloud and on my local machine) are giving me the same error. Have you or you team encountered anything like this? Do you have any advice you could share with me? If you had any pointers, that would be terrific :)

Thanks again, 

D

**Comment by tim-boost** [comment]
The 403 error may indicate an issue with the HARVESTER_API_KEY, see here for information about this https://digitalnz.github.io/supplejack/components/supplejack-manager.html.

Otherwise try spinning down the stack with `docker-compose down` then up again with the build option `docker-compose up --build` in case any old changes exist locally on your machine.

**Comment by telezoic** [comment]
Awesome. 

Thanks @tim-boost! 

I made a new harvester API key and replaced the default values in `docker-compose.yml` and everything is coming through. 

Thanks again!

D
