### ISSUE TITLE
manager repeatedly restarting

### ISSUE THREAD

**Issue by revanar** [DigitalNZ/supplejack_docker#7]
Hi everyone,

I'm attempting to install supplejack on Ubuntu 16.04, but I'm running into an issue where the manager is exiting and restarting repeatedly when I run ```docker-compose up```.

Here is the manager output:

```
manager      | /bundle/gems/airbrake-ruby-1.3.1/lib/airbrake-ruby/notifier.rb:34:in `initialize': both :project_id and :project_key are required (Airbrake::Error)
manager      | 	from /bundle/gems/airbrake-ruby-1.3.1/lib/airbrake-ruby.rb:105:in `new'
manager      | 	from /bundle/gems/airbrake-ruby-1.3.1/lib/airbrake-ruby.rb:105:in `configure'
manager      | 	from /manager/config/initializers/airbrake.rb:10:in `<top (required)>'
manager      | 	from /bundle/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:245:in `load'
manager      | 	from /bundle/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:245:in `block in load'
manager      | 	from /bundle/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:236:in `load_dependency'
manager      | 	from /bundle/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:245:in `load'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/engine.rb:592:in `each'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/engine.rb:592:in `block in <class:Engine>'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/initializable.rb:30:in `instance_exec'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/initializable.rb:30:in `run'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/initializable.rb:55:in `block in run_initializers'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/initializable.rb:54:in `each'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/initializable.rb:54:in `run_initializers'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/application.rb:136:in `initialize!'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
manager      | 	from /manager/config/environment.rb:13:in `<top (required)>'
manager      | 	from /bundle/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
manager      | 	from /bundle/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `block in require'
manager      | 	from /bundle/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:236:in `load_dependency'
manager      | 	from /bundle/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
manager      | 	from /manager/config.ru:3:in `block in <main>'
manager      | 	from /bundle/gems/rack-1.4.7/lib/rack/builder.rb:51:in `instance_eval'
manager      | 	from /bundle/gems/rack-1.4.7/lib/rack/builder.rb:51:in `initialize'
manager      | 	from /manager/config.ru:in `new'
manager      | 	from /manager/config.ru:in `<main>'
manager      | 	from /bundle/gems/rack-1.4.7/lib/rack/builder.rb:40:in `eval'
manager      | 	from /bundle/gems/rack-1.4.7/lib/rack/builder.rb:40:in `parse_file'
manager      | 	from /bundle/gems/rack-1.4.7/lib/rack/server.rb:200:in `app'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/commands/server.rb:46:in `app'
manager      | 	from /bundle/gems/rack-1.4.7/lib/rack/server.rb:304:in `wrapped_app'
manager      | 	from /bundle/gems/rack-1.4.7/lib/rack/server.rb:254:in `start'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/commands/server.rb:70:in `start'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/commands.rb:55:in `block in <top (required)>'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/commands.rb:50:in `tap'
manager      | 	from /bundle/gems/railties-3.2.22.2/lib/rails/commands.rb:50:in `<top (required)>'
manager      | 	from script/rails:6:in `require'
manager      | 	from script/rails:6:in `<main>'
manager      | => Booting Unicorn 
manager      | => Rails 3.2.22.2 application starting in development on http://0.0.0.0:3000
manager      | => Call with -d to detach
manager      | => Ctrl-C to shutdown server
manager      | Exiting
manager exited with code 1
```

I attempted to re-build the image, and got the same result.  I noticed the following errors while rebuilding the image:

(multiple times)
```
debconf: delaying package configuration, since apt-utils is not installed
```
and
```
npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine form-data@2.1.2: wanted: {"node":">= 0.12"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.29","npm":"1.4.21"})
```

Otherwise, it appears to build the container successfully.

Does anyone have any suggestion about what may be going wrong?

Thanks,

-Matt

Edit - Update:

Today I re-provisioned my docker-machine and rebuilt all of the containers, and ended up getting this error:

```
Considering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Could not link global install, skipping...
/tmp/phantomjs is not writable: ENOSPC, no space left on device '/tmp/phantomjs'
/usr/local/lib/node_modules/phantomjs-prebuilt/phantomjs is not writable: ENOSPC, no space left on device '/usr/local/lib/node_modules/phantomjs-prebuilt/phantomjs'
/usr/local/lib/node_modules/phantomjs-prebuilt/tmp/phantomjs is not writable: ENOSPC, no space left on device '/usr/local/lib/node_modules/phantomjs-prebuilt/tmp'
Can not find a writable tmp directory, please report issue on https://github.com/Medium/phantomjs/issues with as much information as possible.
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script.
npm ERR! This is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.4.39-boot2docker
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "phantomjs-prebuilt"
npm ERR! cwd /
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0
ERROR: Service 'manager' failed to build: The command '/bin/sh -c npm install -g phantomjs-prebuilt' returned a non-zero code: 1
```

I'm still unsure of how to get manager working, and any help would be appreciated!

**Comment by telezoic** [comment]
Happy New Year! 

I'm working on a fresh install of this repo with Homebrew on OSX, and I'm seeing mostly the same errors as @revanar  above (we're working together, remotely). 

In the `build` stage:

`debconf: delaying package configuration, since apt-utils is not installed`

`npm WARN engine request@2.79.0: wanted: {"node":">= 4"} (current: {"node":"0.10.29","npm":"1.4.21"}) . . . `

and then in `up` an endlessly restarting manager, that seems to run into trouble at:

`~/bundle/gems/airbrake-ruby-1.3.1/lib/airbrake-ruby/notifier.rb:34:in 'initialize': both :project_id and :project_key are required (Airbrake::Error)` 

I'm sure I've seen this before (in the fall) but I can't recall how it was fixed. 
I can't replicate the PhantomJS errors above however, just the manger bits.

I'm hoping you might have some insights on this. :)

**Comment by telezoic** [comment]
I missed the "Note: inside manager/config folder, copy the application.yml.docker to application.yml" bit here. I will try this again . . .

**Comment by telezoic** [comment]
Sorry about this, my manager is good after making change. I'll do further testing shortly.

**Comment by revanar** [comment]
Hi all,

I tried rebuilding after @telezoic got it up and running, and now mine seems to be working too.  Looking back at my install logs, I think that Docker was having trouble fetching a few resources during the build, but it's fetching them successfully now.  I'm going to go ahead and close this issue.

**Comment by hapiben** [comment]
Hi all,

Just got back from holiday. Great to see everything's working. I'll answer the other open issues.

Cheers,
Ben
